// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arzsawkyieoclveupyrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyenNhd2t5aWVvY2x2ZXVweXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTM5NjksImV4cCI6MjA2MDgyOTk2OX0.bl8CAhVWxBYzr_oPbswOE-fNnoDkYn1Fxzj3fmmuvfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);